FROM node:24-alpine

RUN npm install -g bun

WORKDIR /app

RUN chown node:node /app

USER node

COPY docker/entrypoint.dev.sh /usr/local/bin/entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["entrypoint.sh"]
CMD ["bun", "run", "start:dev"]
