FROM node:24-alpine

RUN npm install -g bun

WORKDIR /app

RUN chown node:node /app

COPY --chown=node:node package.json bun.lock ./

USER node

RUN bun install

COPY --chown=node:node . .

EXPOSE 3001

CMD ["bun", "run", "start:admin:dev"]
