export const BETTER_AUTH_INSTANCE = Symbol("BETTER_AUTH_INSTANCE");
export const AUTH_REDIS_CLIENT = Symbol("AUTH_REDIS_CLIENT");
export const AUTH_SECONDARY_STORAGE = Symbol("AUTH_SECONDARY_STORAGE");
