from __future__ import annotations

import json
import logging

from app.core.graph.router import run_qa_graph
from app.schemas.qa_intelligence import QaTestBreakdown
from app.schemas.queue import AiQaIntelligenceJob, AiQaIntelligenceSucceededResult

logger = logging.getLogger(__name__)


class QaIntelligenceProcessor:
    async def process_job(self, job: AiQaIntelligenceJob) -> AiQaIntelligenceSucceededResult:
        logger.info(
            "QaIntelligenceProcessor | project_id=%s | job_id=%s",
            job.project_id,
            job.job_id,
        )

        breakdown: QaTestBreakdown = await run_qa_graph(job)

        content = _render_markdown(breakdown)
        title = f"Test Suite — {breakdown.project_name}"

        suite_count = len(breakdown.test_suites)
        test_count = sum(len(s.test_cases) for s in breakdown.test_suites)

        logger.info(
            "QaIntelligenceProcessor | project_id=%s | suites=%d | tests=%d",
            job.project_id,
            suite_count,
            test_count,
        )

        return AiQaIntelligenceSucceededResult(
            jobId=job.job_id,
            projectId=job.project_id,
            userId=job.user_id,
            content=content,
            title=title,
        )


def _render_markdown(breakdown: QaTestBreakdown) -> str:
    """Convert QaTestBreakdown to Markdown for storage as a Documentation record."""
    lines: list[str] = [
        f"# Test Suite — {breakdown.project_name}",
        "",
        f"*Generated by QA Intelligence Agent · {len(breakdown.test_suites)} feature(s) · "
        f"{sum(len(s.test_cases) for s in breakdown.test_suites)} test case(s)*",
        "",
    ]

    for suite in breakdown.test_suites:
        lines += [
            f"---",
            "",
            f"## {suite.feature_name} (`{suite.feature_id}`)",
            "",
        ]

        if suite.acceptance_criteria:
            lines.append("### Acceptance Criteria")
            lines.append("")
            for criterion in suite.acceptance_criteria:
                lines.append(f"- {criterion}")
            lines.append("")

        if suite.test_cases:
            lines.append("### Test Cases")
            lines.append("")
            for tc in suite.test_cases:
                req_note = f" · `{tc.requirement_id}`" if tc.requirement_id else ""
                lines += [
                    f"#### [{tc.id}] {tc.title}",
                    "",
                    f"**Type:** `{tc.type}`{req_note}",
                    "",
                ]

                if tc.preconditions:
                    lines.append("**Preconditions:**")
                    for pre in tc.preconditions:
                        lines.append(f"- {pre}")
                    lines.append("")

                if tc.steps:
                    lines.append("**Steps:**")
                    for i, step in enumerate(tc.steps, start=1):
                        lines.append(f"{i}. {step}")
                    lines.append("")

                lines += [
                    f"**Expected Result:** {tc.expected_result}",
                    "",
                ]

    return "\n".join(lines)
